### ISSUE TITLE
Not possible to use the cds Enhanced with the layout search

### ISSUE THREAD

**Issue by nevakee716** [nevakee716/Search#1]

**Comment by JGrndn** [comment]
Opening popout with search layout causes troubles :
Click on "popout" icon will open the options panel as well. The options panel cannot be closed and area with the list of result will be empty

**Comment by JGrndn** [comment]
Empty result --> see issue #3

**Comment by JGrndn** [comment]
Opening popout is now possible as the options panel has been disabled. Closing this issue and creating a new one regarding the options panel. 
See #4
